
export const FETCH_FOODDATA_REQUEST = "FETCH_FOODDATA_REQUEST"
export const FETCH_FOODDATA_SUCCESS = "FETCH_FOODDATA_SUCCESS"
export const FETCH_FOODDATA_FAILED = "FETCH_FOODDATA_FAILED"


export const POST_USERDATA_REQUEST = "POST_USERDATA_REQUEST"
export const POST_USERDATA_SUCCESS = "POST_USERDATA_SUCCESS"
export const POST_USERDATA_FAILED = "POST_USERDATA_FAILED"


export const DELETE_SINGLEDATA_REQUEST = "DELETE_SINGLEDATA_REQUEST"
export const DELETE_SINGLEDATA_SUCCESS = "DELETE_SINGLEDATA_SUCCESS"
export const DELETE_SINGLEDATA_FAILED = "DELETE_SINGLEDATA_FAILED"